# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 00:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('det1', 'det1'), ('det2', 'det2'), ('det3', 'det3'), ('det4', 'det4'), ('det5', 'det5')], default=None, max_length=10, null=True)),
                ('taxi', models.IntegerField(default=10)),
                ('bus', models.IntegerField(default=8)),
                ('underground', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('complete', models.BooleanField(default=False)),
                ('player1_is_x', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MrX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxi', models.IntegerField(default=4)),
                ('bus', models.IntegerField(default=3)),
                ('underground', models.IntegerField(default=3)),
                ('black', models.IntegerField(default=5)),
                ('x2', models.IntegerField(default=2)),
                ('game', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mrx', to='syard_main.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('mrx_loc', models.IntegerField(null=True)),
                ('det1_loc', models.IntegerField(null=True)),
                ('det2_loc', models.IntegerField(null=True)),
                ('det3_loc', models.IntegerField(null=True)),
                ('det4_loc', models.IntegerField(null=True)),
                ('det5_loc', models.IntegerField(null=True)),
                ('num', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='syard_main.Game')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='_userprofile_friends_+', to='syard_main.UserProfile')),
                ('games', models.ManyToManyField(blank=True, db_index=True, related_name='users', to='syard_main.Game')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='syard_main.UserProfile'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='syard_main.UserProfile'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='syard_main.UserProfile'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detective',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dets', to='syard_main.Game'),
        ),
    ]
