# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syard_main', '0002_auto_20160502_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('det1', 'det1'), ('det2', 'det2'), ('det3', 'det3'), ('det4', 'det4'), ('det5', 'det5')], default=None, max_length=10, null=True)),
                ('taxi', models.IntegerField(default=10)),
                ('bus', models.IntegerField(default=8)),
                ('underground', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='MrX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxi', models.IntegerField(default=4)),
                ('bus', models.IntegerField(default=3)),
                ('underground', models.IntegerField(default=3)),
                ('black', models.IntegerField(default=5)),
                ('x2', models.IntegerField(default=2)),
            ],
        ),
        migrations.RenameField(
            model_name='round',
            old_name='blue_loc',
            new_name='det1_loc',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='green_loc',
            new_name='det2_loc',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='purple_loc',
            new_name='det3_loc',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='red_loc',
            new_name='det4_loc',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='yellow_loc',
            new_name='det5_loc',
        ),
        migrations.AddField(
            model_name='game',
            name='player1_is_x',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='round',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_friends_+', to='syard_main.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='games',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='player', to='syard_main.Game'),
        ),
        migrations.AddField(
            model_name='mrx',
            name='game',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mrx', to='syard_main.Game'),
        ),
        migrations.AddField(
            model_name='detective',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dets', to='syard_main.Game'),
        ),
    ]
