# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syard_main', '0003_auto_20160503_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='games',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='players', to='syard_main.Game'),
        ),
    ]
