# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syard_main', '0003_auto_20160503_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
