# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 19:50
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('syard_main', '0004_auto_20160503_1936'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
