# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syard_main', '0005_auto_20160503_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='syard_main.UserProfile'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='syard_main.UserProfile'),
        ),
        migrations.AlterField(
            model_name='game',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='syard_main.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='games',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='users', to='syard_main.Game'),
        ),
    ]
